// options.js
export const COUNTRIES = [
    { label: 'Afghanistan', value: 'Afghanistan (af)' },
    { label: 'Albania', value: 'Albania (al)' },
    { label: 'Algeria', value: 'Algeria (dz)' },
    { label: 'Andorra', value: 'Andorra (ad)' },
    { label: 'Angola', value: 'Angola (ao)' },
    { label: 'Antigua and Barbuda', value: 'Antigua and Barbuda (ag)' },
    { label: 'Argentina', value: 'Argentina (ar)' },
    { label: 'Armenia', value: 'Armenia (am)' },
    { label: 'Australia', value: 'Australia (au)' },
    { label: 'Austria', value: 'Austria (at)' },
    { label: 'Azerbaijan', value: 'Azerbaijan (az)' },
    { label: 'Bahamas', value: 'Bahamas (bs)' },
    { label: 'Bahrain', value: 'Bahrain (bh)' },
    { label: 'Bangladesh', value: 'Bangladesh (bd)' },
    { label: 'Barbados', value: 'Barbados (bb)' },
    { label: 'Belarus', value: 'Belarus (by)' },
    { label: 'Belgium', value: 'Belgium (be)' },
    { label: 'Belize', value: 'Belize (bz)' },
    { label: 'Benin', value: 'Benin (bj)' },
    { label: 'Bhutan', value: 'Bhutan (bt)' },
    { label: 'Bolivia', value: 'Bolivia (bo)' },
    { label: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina (ba)' },
    { label: 'Botswana', value: 'Botswana (bw)' },
    { label: 'Brazil', value: 'Brazil (br)' },
    { label: 'Brunei', value: 'Brunei (bn)' },
    { label: 'Bulgaria', value: 'Bulgaria (bg)' },
    { label: 'Burkina Faso', value: 'Burkina Faso (bf)' },
    { label: 'Burundi', value: 'Burundi (bi)' },
    { label: 'Cabo Verde', value: 'Cabo Verde (cv)' },
    { label: 'Cambodia', value: 'Cambodia (kh)' },
    { label: 'Cameroon', value: 'Cameroon (cm)' },
    { label: 'Canada', value: 'Canada (ca)' },
    { label: 'Central African Republic', value: 'Central African Republic (cf)' },
    { label: 'Chad', value: 'Chad (td)' },
    { label: 'Chile', value: 'Chile (cl)' },
    { label: 'China', value: 'China (cn)' },
    { label: 'Colombia', value: 'Colombia (co)' },
    { label: 'Comoros', value: 'Comoros (km)' },
    { label: 'Congo (Congo-Brazzaville)', value: 'Congo (Congo-Brazzaville) (cg)' },
    { label: 'Costa Rica', value: 'Costa Rica (cr)' },
    { label: 'Croatia', value: 'Croatia (hr)' },
    { label: 'Cuba', value: 'Cuba (cu)' },
    { label: 'Cyprus', value: 'Cyprus (cy)' },
    { label: 'Czech Republic', value: 'Czech Republic (cz)' },
    { label: 'Denmark', value: 'Denmark (dk)' },
    { label: 'Djibouti', value: 'Djibouti (dj)' },
    { label: 'Dominica', value: 'Dominica (dm)' },
    { label: 'Dominican Republic', value: 'Dominican Republic (do)' },
    { label: 'Ecuador', value: 'Ecuador (ec)' },
    { label: 'Egypt', value: 'Egypt (eg)' },
    { label: 'El Salvador', value: 'El Salvador (sv)' },
    { label: 'Equatorial Guinea', value: 'Equatorial Guinea (gq)' },
    { label: 'Eritrea', value: 'Eritrea (er)' },
    { label: 'Estonia', value: 'Estonia (ee)' },
    { label: 'Eswatini', value: 'Eswatini (sz)' },
    { label: 'Ethiopia', value: 'Ethiopia (et)' },
    { label: 'Fiji', value: 'Fiji (fj)' },
    { label: 'Finland', value: 'Finland (fi)' },
    { label: 'France', value: 'France (fr)' },
    { label: 'Gabon', value: 'Gabon (ga)' },
    { label: 'Gambia', value: 'Gambia (gm)' },
    { label: 'Georgia', value: 'Georgia (ge)' },
    { label: 'Germany', value: 'Germany (de)' },
    { label: 'Ghana', value: 'Ghana (gh)' },
    { label: 'Greece', value: 'Greece (gr)' },
    { label: 'Grenada', value: 'Grenada (gd)' },
    { label: 'Guatemala', value: 'Guatemala (gt)' },
    { label: 'Guinea', value: 'Guinea (gn)' },
    { label: 'Guinea-Bissau', value: 'Guinea-Bissau (gw)' },
    { label: 'Guyana', value: 'Guyana (gy)' },
    { label: 'Haiti', value: 'Haiti (ht)' },
    { label: 'Honduras', value: 'Honduras (hn)' },
    { label: 'Hungary', value: 'Hungary (hu)' },
    { label: 'Iceland', value: 'Iceland (is)' },
    { label: 'India', value: 'India (in)' },
    { label: 'Indonesia', value: 'Indonesia (id)' },
    { label: 'Iran', value: 'Iran (ir)' },
    { label: 'Iraq', value: 'Iraq (iq)' },
    { label: 'Ireland', value: 'Ireland (ie)' },
    { label: 'Israel', value: 'Israel (il)' },
    { label: 'Italy', value: 'Italy (it)' },
    { label: 'Jamaica', value: 'Jamaica (jm)' },
    { label: 'Japan', value: 'Japan (jp)' },
    { label: 'Jordan', value: 'Jordan (jo)' },
    { label: 'Kazakhstan', value: 'Kazakhstan (kz)' },
    { label: 'Kenya', value: 'Kenya (ke)' },
    { label: 'Kiribati', value: 'Kiribati (ki)' },
    { label: 'Kuwait', value: 'Kuwait (kw)' },
    { label: 'Kyrgyzstan', value: 'Kyrgyzstan (kg)' },
    { label: 'Laos', value: 'Laos (la)' },
    { label: 'Latvia', value: 'Latvia (lv)' },
    { label: 'Lebanon', value: 'Lebanon (lb)' },
    { label: 'Lesotho', value: 'Lesotho (ls)' },
    { label: 'Liberia', value: 'Liberia (lr)' },
    { label: 'Libya', value: 'Libya (ly)' },
    { label: 'Liechtenstein', value: 'Liechtenstein (li)' },
    { label: 'Lithuania', value: 'Lithuania (lt)' },
    { label: 'Luxembourg', value: 'Luxembourg (lu)' },
    { label: 'Madagascar', value: 'Madagascar (mg)' },
    { label: 'Malawi', value: 'Malawi (mw)' },
    { label: 'Malaysia', value: 'Malaysia (my)' },
    { label: 'Maldives', value: 'Maldives (mv)' },
    { label: 'Mali', value: 'Mali (ml)' },
    { label: 'Malta', value: 'Malta (mt)' },
    { label: 'Marshall Islands', value: 'Marshall Islands (mh)' },
    { label: 'Mauritania', value: 'Mauritania (mr)' },
    { label: 'Mauritius', value: 'Mauritius (mu)' },
    { label: 'Mexico', value: 'Mexico (mx)' },
    { label: 'Micronesia', value: 'Micronesia (fm)' },
    { label: 'Moldova', value: 'Moldova (md)' },
    { label: 'Monaco', value: 'Monaco (mc)' },
    { label: 'Mongolia', value: 'Mongolia (mn)' },
    { label: 'Montenegro', value: 'Montenegro (me)' },
    { label: 'Morocco', value: 'Morocco (ma)' },
    { label: 'Mozambique', value: 'Mozambique (mz)' },
    { label: 'Myanmar (formerly Burma)', value: 'Myanmar (formerly Burma) (mm)' },
    { label: 'Namibia', value: 'Namibia (na)' },
    { label: 'Nauru', value: 'Nauru (nr)' },
    { label: 'Nepal', value: 'Nepal (np)' },
    { label: 'Netherlands', value: 'Netherlands (nl)' },
    { label: 'New Zealand', value: 'New Zealand (nz)' },
    { label: 'Nicaragua', value: 'Nicaragua (ni)' },
    { label: 'Niger', value: 'Niger (ne)' },
    { label: 'Nigeria', value: 'Nigeria (ng)' },
    { label: 'North Korea', value: 'North Korea (kp)' },
    { label: 'North Macedonia', value: 'North Macedonia (mk)' },
    { label: 'Norway', value: 'Norway (no)' },
    { label: 'Oman', value: 'Oman (om)' },
    { label: 'Pakistan', value: 'Pakistan (pk)' },
    { label: 'Palau', value: 'Palau (pw)' },
    { label: 'Palestine State', value: 'Palestine State (ps)' },
    { label: 'Panama', value: 'Panama (pa)' },
    { label: 'Papua New Guinea', value: 'Papua New Guinea (pg)' },
    { label: 'Paraguay', value: 'Paraguay (py)' },
    { label: 'Peru', value: 'Peru (pe)' },
    { label: 'Philippines', value: 'Philippines (ph)' },
    { label: 'Poland', value: 'Poland (pl)' },
    { label: 'Portugal', value: 'Portugal (pt)' },
    { label: 'Qatar', value: 'Qatar (qa)' },
    { label: 'Romania', value: 'Romania (ro)' },
    { label: 'Russia', value: 'Russia (ru)' },
    { label: 'Rwanda', value: 'Rwanda (rw)' },
    { label: 'Saint Kitts and Nevis', value: 'Saint Kitts and Nevis (kn)' },
    { label: 'Saint Lucia', value: 'Saint Lucia (lc)' },
    { label: 'Saint Vincent and the Grenadines', value: 'Saint Vincent and the Grenadines (vc)' },
    { label: 'Samoa', value: 'Samoa (ws)' },
    { label: 'San Marino', value: 'San Marino (sm)' },
    { label: 'Sao Tome and Principe', value: 'Sao Tome and Principe (st)' },
    { label: 'Saudi Arabia', value: 'Saudi Arabia (sa)' },
    { label: 'Senegal', value: 'Senegal (sn)' },
    { label: 'Serbia', value: 'Serbia (rs)' },
    { label: 'Seychelles', value: 'Seychelles (sc)' },
    { label: 'Sierra Leone', value: 'Sierra Leone (sl)' },
    { label: 'Singapore', value: 'Singapore (sg)' },
    { label: 'Slovakia', value: 'Slovakia (sk)' },
    { label: 'Slovenia', value: 'Slovenia (si)' },
    { label: 'Solomon Islands', value: 'Solomon Islands (sb)' },
    { label: 'Somalia', value: 'Somalia (so)' },
    { label: 'South Africa', value: 'South Africa (za)' },
    { label: 'South Korea', value: 'South Korea (kr)' },
    { label: 'South Sudan', value: 'South Sudan (ss)' },
    { label: 'Spain', value: 'Spain (es)' },
    { label: 'Sri Lanka', value: 'Sri Lanka (lk)' },
    { label: 'Sudan', value: 'Sudan (sd)' },
    { label: 'Suriname', value: 'Suriname (sr)' },
    { label: 'Sweden', value: 'Sweden (se)' },
    { label: 'Switzerland', value: 'Switzerland (ch)' },
    { label: 'Syria', value: 'Syria (sy)' },
    { label: 'Taiwan', value: 'Taiwan (tw)' },
    { label: 'Tajikistan', value: 'Tajikistan (tj)' },
    { label: 'Tanzania', value: 'Tanzania (tz)' },
    { label: 'Thailand', value: 'Thailand (th)' },
    { label: 'Timor-Leste', value: 'Timor-Leste (tl)' },
    { label: 'Togo', value: 'Togo (tg)' },
    { label: 'Tonga', value: 'Tonga (to)' },
    { label: 'Trinidad and Tobago', value: 'Trinidad and Tobago (tt)' },
    { label: 'Tunisia', value: 'Tunisia (tn)' },
    { label: 'Turkey', value: 'Turkey (tr)' },
    { label: 'Turkmenistan', value: 'Turkmenistan (tm)' },
    { label: 'Tuvalu', value: 'Tuvalu (tv)' },
    { label: 'Uganda', value: 'Uganda (ug)' },
    { label: 'Ukraine', value: 'Ukraine (ua)' },
    { label: 'United Arab Emirates', value: 'United Arab Emirates (ae)' },
    { label: 'United Kingdom', value: 'United Kingdom (uk)' },
    { label: 'United States', value: 'United States (us)' },
    { label: 'Uruguay', value: 'Uruguay (uy)' },
    { label: 'Uzbekistan', value: 'Uzbekistan (uz)' },
    { label: 'Vanuatu', value: 'Vanuatu (vu)' },
    { label: 'Vatican City', value: 'Vatican City (va)' },
    { label: 'Venezuela', value: 'Venezuela (ve)' },
    { label: 'Vietnam', value: 'Vietnam (vn)' },
    { label: 'Yemen', value: 'Yemen (ye)' },
    { label: 'Zambia', value: 'Zambia (zm)' },
    { label: 'Zimbabwe', value: 'Zimbabwe (zw)' }
];

export const US_STATES = [
    { label: 'Alabama', value: 'Alabama (AL)' },
    { label: 'Alaska', value: 'Alaska (AK)' },
    { label: 'Arizona', value: 'Arizona (AZ)' },
    { label: 'Arkansas', value: 'Arkansas (AR)' },
    { label: 'California', value: 'California (CA)' },
    { label: 'Colorado', value: 'Colorado (CO)' },
    { label: 'Connecticut', value: 'Connecticut (CT)' },
    { label: 'Delaware', value: 'Delaware (DE)' },
    { label: 'Florida', value: 'Florida (FL)' },
    { label: 'Georgia', value: 'Georgia (GA)' },
    { label: 'Hawaii', value: 'Hawaii (HI)' },
    { label: 'Idaho', value: 'Idaho (ID)' },
    { label: 'Illinois', value: 'Illinois (IL)' },
    { label: 'Indiana', value: 'Indiana (IN)' },
    { label: 'Iowa', value: 'Iowa (IA)' },
    { label: 'Kansas', value: 'Kansas (KS)' },
    { label: 'Kentucky', value: 'Kentucky (KY)' },
    { label: 'Louisiana', value: 'Louisiana (LA)' },
    { label: 'Maine', value: 'Maine (ME)' },
    { label: 'Maryland', value: 'Maryland (MD)' },
    { label: 'Massachusetts', value: 'Massachusetts (MA)' },
    { label: 'Michigan', value: 'Michigan (MI)' },
    { label: 'Minnesota', value: 'Minnesota (MN)' },
    { label: 'Mississippi', value: 'Mississippi (MS)' },
    { label: 'Missouri', value: 'Missouri (MO)' },
    { label: 'Montana', value: 'Montana (MT)' },
    { label: 'Nebraska', value: 'Nebraska (NE)' },
    { label: 'Nevada', value: 'Nevada (NV)' },
    { label: 'New Hampshire', value: 'New Hampshire (NH)' },
    { label: 'New Jersey', value: 'New Jersey (NJ)' },
    { label: 'New Mexico', value: 'New Mexico (NM)' },
    { label: 'New York', value: 'New York (NY)' },
    { label: 'North Carolina', value: 'North Carolina (NC)' },
    { label: 'North Dakota', value: 'North Dakota (ND)' },
    { label: 'Ohio', value: 'Ohio (OH)' },
    { label: 'Oklahoma', value: 'Oklahoma (OK)' },
    { label: 'Oregon', value: 'Oregon (OR)' },
    { label: 'Pennsylvania', value: 'Pennsylvania (PA)' },
    { label: 'Rhode Island', value: 'Rhode Island (RI)' },
    { label: 'South Carolina', value: 'South Carolina (SC)' },
    { label: 'South Dakota', value: 'South Dakota (SD)' },
    { label: 'Tennessee', value: 'Tennessee (TN)' },
    { label: 'Texas', value: 'Texas (TX)' },
    { label: 'Utah', value: 'Utah (UT)' },
    { label: 'Vermont', value: 'Vermont (VT)' },
    { label: 'Virginia', value: 'Virginia (VA)' },
    { label: 'Washington', value: 'Washington (WA)' },
    { label: 'West Virginia', value: 'West Virginia (WV)' },
    { label: 'Wisconsin', value: 'Wisconsin (WI)' },
    { label: 'Wyoming', value: 'Wyoming (WY)' }
];
